---
- src: git+https://github.com/haf/ansible-kafka.git
  version: v1.0.8
- src: git+https://github.com/haf/ansible-zookeeper.git
  version: v1.0.8
- src: yatesr.timezone
  version: 1.0.0
- src: ansiblebit.oracle-java
  version: 4.14.4
