---
- hosts: all
  become: True

  roles:
    - ufw
    - yatesr.timezone
    - sansible.kafka
    - sansible.zookeeper

  tasks:
    - name: Update and upgrade packages
      apt: update_cache=yes cache_valid_time=3600 upgrade=dist

    - name: Configure vm.swappiness
      lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = 0" regexp="^vm.swappiness[\s]?=" state=present

    - name: Enable unattended security updates
      lineinfile:
        dest: /etc/apt/apt.conf.d/10periodic
        regexp: "^{{ item.key }} "
        line: '{{ item.key }} "{{ item.value }}";'
        state: present
      with_items:
        - { key: "APT::Periodic::Update-Package-Lists", value: "1" }
        - { key: "APT::Periodic::Download-Upgradeable-Packages", value: "1" }
        - { key: "APT::Periodic::AutocleanInterval", value: "7" }
        - { key: "APT::Periodic::Unattended-Upgrade", value: "1" }

    - name: Set timezone
      command: timedatectl set-timezone {{ timezone }}

    - name: Install NTP
      apt: pkg=ntp state=present
